### ISSUE TITLE
release tracking issue

### ISSUE THREAD

**Issue by Johann150** [brendanzab/codespan#298]
A lot of stuff has already changed and fixed since the last release. But there is still some stuff that has to be done.

### REQUIRED
- [x] decide on refactoring of error types (#295)
- [x] fix `codespan` readme (still has gitter badge)
- [x] increment version number (there are some breaking changes)
- [x] check changelog (most of the stuff should've been covered in c9f640bf7161258bc30b6f432bdbe2612c9bc1f0 already)
### OPTIONAL
- ~resolve #272~ (process could be tested with this release)
- [x] merge #297 so there is not another breaking version update right again

**Comment by brendanzab** [comment]
Thinking that we might be able to bump the version of `codespan-reporting` from to 0.9.5 to 0.10.2, if we want to bring things back in sync with `codespan-lsp`, which is currently on 0.10.1.

We might also need to add in the extra changelog entries that were missed in `codespan-lsp` 0.10.0 and 0.10.1.

**Comment by Johann150** [comment]
I don't think there is a codespan-lsp release 0.10.1 yet. Its Cargo.toml still specifies an alpha version of 0.10.2.

**Comment by brendanzab** [comment]
Yeah, I mean that we would need to publish a new version of `codespan-lsp` that bumped the dependency on `codespan`. Either that or to re-sync the versions we'd need to skip a version of `codespan`. Or we could keep them out of sync until we end up folding `codespan-lsp` into `codespan`.

**Comment by Johann150** [comment]
I think it would be good to have the versions in sync. E.g. if you look at the current changelog for `codespan-lsp`, you will notice that it is currently broken because there are missing tags for the versions. Since this is a mono-repo, there can always only be one tag per version. Thus it would be nice to sync them again. Plus it wont be a breaking change to `codespan-lsp`, so a patch version increment should be fine.

**Comment by Johann150** [comment]
Regarding #272, it would be smart to test it out with this release (i.e. that issue will not be solved before this release).
